server:
  port: 8102

spring:
  application:
    name: product-service
  config:
    import: nacos:product-service.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        shared-configs:
          - data-id: common-config.yaml
            group: DEFAULT_GROUP
            refresh: true
    stream:
      function:
        definition: paymentSuccess;refundSuccess
      bindings:
        paymentSuccess-in-0:
          destination: payment-success
          group: ${spring.application.name}-group
          consumer:
            max-attempts: 3
        refundSuccess-in-0:
          destination: refund-success
          group: ${spring.application.name}-group
          consumer:
            max-attempts: 3
      rabbit:
        bindings:
          paymentSuccess-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
          refundSuccess-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true