server:
  port: 8104

spring:
  application:
    name: payment-service
  config:
    import: nacos:${spring.application.name}.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_payment?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        shared-configs:
          - data-id: common-config.yaml
            group: DEFAULT_GROUP
            refresh: true
    sentinel:
      transport:
        dashboard: localhost:8720
        port: 8723
      eager: true
    stream:
      default-binder: rabbit
      bindings:
        paymentSuccess-out-0:
          destination: payment-success
          content-type: application/json
        refundSuccess-out-0:
          destination: refund-success
          content-type: application/json

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

knife4j:
  enable: true

logging:
  level:
    com.ecommerce: debug

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
