server:
  port: 8108

spring:
  application:
    name: marketing-service
  config:
    import: nacos:${spring.application.name}.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_marketing?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        shared-configs:
          - data-id: common-config.yaml
            group: DEFAULT_GROUP
            refresh: true
    sentinel:
      transport:
        dashboard: localhost:8720
        port: 8727
      eager: true

    stream:
      default-binder: rabbit
      function:
        definition: couponUse
      bindings:
        couponUse-in-0:
          destination: coupon-use
          group: ${spring.application.name}
          content-type: application/json
      rabbit:
        bindings:
          couponUse-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.ecommerce.marketing.model.entity

knife4j:
  enable: true

logging:
  level:
    com.ecommerce: debug

seata:
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: SEATA_GROUP
  tx-service-group: ecommerce-tx-group
  service:
    vgroup-mapping:
      ecommerce-tx-group: default
  data-source-proxy-mode: AT

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
