server:
  port: 8108

spring:
  application:
    name: marketing-service
  config:
    import: nacos:marketing-service.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        shared-configs:
          - data-id: common-config.yaml
            group: DEFAULT_GROUP
            refresh: true
    stream:
      function:
        definition: couponUse
      bindings:
        couponUse-in-0:
          destination: coupon-use
          group: ${spring.application.name}-group
          consumer:
            max-attempts: 3
      rabbit:
        bindings:
          couponUse-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true