CREATE DATABASE IF NOT EXISTS db_product DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE db_product;

CREATE TABLE t_category (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '分类ID',
    name VARCHAR(50) NOT NULL COMMENT '分类名称',
    parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '父分类ID, 0为顶级',
    level TINYINT NOT NULL DEFAULT 1 COMMENT '层级',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    icon VARCHAR(255) DEFAULT NULL COMMENT '图标',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_parent_id (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品分类表';

CREATE TABLE t_brand (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '品牌ID',
    name VARCHAR(100) NOT NULL COMMENT '品牌名称',
    logo VARCHAR(255) DEFAULT NULL COMMENT '品牌Logo',
    description VARCHAR(500) DEFAULT NULL COMMENT '品牌描述',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 1启用 0禁用',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='品牌表';

CREATE TABLE t_product (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '商品ID',
    name VARCHAR(200) NOT NULL COMMENT '商品名称',
    category_id BIGINT NOT NULL COMMENT '分类ID',
    brand_id BIGINT DEFAULT NULL COMMENT '品牌ID',
    main_image VARCHAR(255) DEFAULT NULL COMMENT '主图',
    images TEXT DEFAULT NULL COMMENT '商品图片集(JSON数组)',
    description TEXT DEFAULT NULL COMMENT '商品描述(富文本)',
    unit VARCHAR(20) DEFAULT NULL COMMENT '计量单位',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 1上架 0下架',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    KEY idx_category_id (category_id),
    KEY idx_brand_id (brand_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品表';

CREATE TABLE t_spec_group (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '规格组ID',
    name VARCHAR(50) NOT NULL COMMENT '规格组名称(如:颜色、尺寸)',
    category_id BIGINT NOT NULL COMMENT '分类ID',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    KEY idx_category_id (category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='规格组表';

CREATE TABLE t_spec_param (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '规格参数ID',
    group_id BIGINT NOT NULL COMMENT '规格组ID',
    name VARCHAR(50) NOT NULL COMMENT '参数名',
    `values` TEXT NOT NULL COMMENT '可选值(JSON数组)',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    KEY idx_group_id (group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='规格参数表';

CREATE TABLE t_sku (
    id BIGINT NOT NULL PRIMARY KEY COMMENT 'SKU ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    sku_code VARCHAR(100) NOT NULL COMMENT 'SKU编码',
    spec_values JSON NOT NULL COMMENT '规格值如:{"颜色":"红色","尺寸":"XL"}',
    price DECIMAL(12,2) NOT NULL COMMENT '售价',
    market_price DECIMAL(12,2) DEFAULT NULL COMMENT '市场价',
    weight DECIMAL(10,2) DEFAULT NULL COMMENT '重量(g)',
    image VARCHAR(255) DEFAULT NULL COMMENT 'SKU图片',
    stock INT NOT NULL DEFAULT 0 COMMENT '库存',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 1启用 0禁用',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_sku_code (sku_code),
    KEY idx_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SKU表';
